export const dummyPosts = [
  {
    id: 1,
    title: '첫번째 포스트',
    image: 'images/photo_test1.jpeg',
    location: '대구',
    people: 2,
    option_gender: '성별무관',
    option_type: '힐링',
    start_date: '2022.03.12',
    finish_date: '2022.03.12',
  },
  {
    id: 2,
    title: '제목이 길면 어떻게 될까요오오오',
    image: 'images/photo_test1.jpeg',
    location: '부산',
    people: 5,
    option_gender: '여자만',
    option_type: '익스트림',
    start_date: '2022.03.12',
    finish_date: '2022.03.12',
  },
  {
    id: 3,
    title: '너 나의 동료가 되어라',
    image: 'images/photo_test1.jpeg',
    location: '대구',
    people: 3,
    option_gender: '성별무관',
    option_type: '익스트림',
    start_date: '2022.03.12',
    finish_date: '2022.03.12',
  },
  {
    id: 4,
    title: '너 나의 동료가 되어라',
    image: 'images/photo_test1.jpeg',
    location: '대구',
    people: 10,
    option_gender: '성별무관',
    option_type: '식도락',
    start_date: '2022.03.12',
    finish_date: '2022.03.12',
  },
  {
    id: 5,
    title: '너 나의 동료가 되어라',
    image: 'images/photo_test1.jpeg',
    location: '강원도',
    people: 5,
    option_gender: '성별무관',
    option_type: '익스트림',
    start_date: '2022.03.14',
    finish_date: '2022.03.14',
  },
  {
    id: 6,
    title: '너 나의 동료가 되어라',
    image: 'images/photo_test1.jpeg',
    location: '여수',
    people: 10,
    option_gender: '남자만',
    option_type: '호캉스',
    start_date: '2022.03.15',
    finish_date: '2022.03.15',
  },
  {
    id: 7,
    title: '마지막 포스트',
    image: 'images/photo_test1.jpeg',
    location: '여수',
    people: 10,
    option_gender: '남자만',
    option_type: '익스트림',
    start_date: '2022.03.15',
    finish_date: '2022.03.15',
  },
];
